spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/auctionapp
        username: velid
        password: password
    jpa:
        properties:
            dialect:
                hibernate: org.hibernate.dialect.PostgreSQLDialect
            hibernate:
                #show_sql: true
                format_sql: true
                globally_quoted_identifiers: true
        hibernate:
            ddl-auto: update
