spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/auctionapp
        username: velid
        password: password
    jpa:
        properties:
            dialect:
                hibernate: org.hibernate.dialect.PostgreSQLDialect
            hibernate:
                format_sql: true
                globally_quoted_identifiers: true
        hibernate:
            ddl-auto: update
app:
    jwtSecret: ${TOKEN_SECRET}
    jwtExpiration: 86400000
    stripeSecret: ${STRIPE_SECRET}

external:
    firebase:
        apiKey: ${FIREBASE_API_KEY}
        authDomain: auctionapp-bdab8.firebaseapp.com
        projectId: auctionapp-bdab8
        storageBucket: auctionapp-bdab8.appspot.com
        messagingSenderId: 784939104553
        appId: 1:784939104553:web:c0ec95994284dca21b1f38
        measurementId: G-2TNKQ0LQWR
    stripe:
        stripeSecret: ${STRIPE_SECRET}
